"""empty message

Revision ID: 0bad6b0f4ae5
Revises: bad3455643f1
Create Date: 2022-11-09 18:37:07.974842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bad6b0f4ae5'
down_revision = 'bad3455643f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_carpool_part_passenger_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_carpool_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generated_carpool_id'], ['generated_carpool_parts.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_carpool_part_passenger_links')
    # ### end Alembic commands ###
