"""empty message

Revision ID: 18cd6c449934
Revises: b5d383c84ec2
Create Date: 2022-11-21 14:43:51.023260

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '18cd6c449934'
down_revision = 'b5d383c84ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user_links',
                    sa.Column('user1_id', sa.Integer(), nullable=False),
                    sa.Column('user2_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(length=100), nullable=False),
                    sa.Column('good', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user1_id', 'user2_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_user_links')
    # ### end Alembic commands ###
