"""empty message

Revision ID: 3b1cb9d6b7b1
Revises: 91db9af77926
Create Date: 2022-11-16 09:35:42.471672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1cb9d6b7b1'
down_revision = '91db9af77926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("UPDATE users SET password = 'password' WHERE password IS NULL")
    op.alter_column('users', 'password', nullable=False)
        
    op.alter_column('users', 'passenger_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute("UPDATE users SET passenger_id = 0 WHERE passenger_id IS NULL")
    op.alter_column('users', 'passenger_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passenger_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'destination_id')
    # ### end Alembic commands ###
