"""empty message

Revision ID: 44d833d2c46e
Revises: e7f22b2e6e0b
Create Date: 2022-11-21 18:28:02.865402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d833d2c46e'
down_revision = 'e7f22b2e6e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('needs_matching_build', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'needs_matching_build')
    # ### end Alembic commands ###
