"""empty message

Revision ID: 91db9af77926
Revises: 960f7bff3245
Create Date: 2022-11-15 13:35:33.665052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91db9af77926'
down_revision = '960f7bff3245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pool_points', sa.Float(), nullable=True))
    op.execute("UPDATE users SET pool_points = 0 WHERE pool_points IS NULL")
    op.alter_column('users', 'pool_points', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pool_points')
    # ### end Alembic commands ###
