"""empty message

Revision ID: 960f7bff3245
Revises: cbbb273d7902
Create Date: 2022-11-15 11:10:13.033815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960f7bff3245'
down_revision = 'cbbb273d7902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_carpool_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('willing_to_drive', sa.Boolean(), nullable=False),
    sa.Column('needs_ride', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.index'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_carpool_signups')
    # ### end Alembic commands ###
