"""empty message

Revision ID: b19fb18e416e
Revises: ea4e8bf5d89e
Create Date: 2022-12-02 14:52:28.632690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b19fb18e416e'
down_revision = 'ea4e8bf5d89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('matching_build_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'matching_build_type')

    # ### end Alembic commands ###
