"""empty message

Revision ID: bad3455643f1
Revises: 5ba8bf93a1b7
Create Date: 2022-11-09 18:25:48.197284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad3455643f1'
down_revision = '5ba8bf93a1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpool_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_value', sa.Float(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_carpools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('carpool_solution_id', sa.Integer(), nullable=False),
    sa.Column('from_address_id', sa.Integer(), nullable=False),
    sa.Column('to_address_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carpool_solution_id'], ['carpool_solutions.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.index'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.index'], ),
    sa.ForeignKeyConstraint(['from_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['to_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_carpool_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('generated_carpool_id', sa.Integer(), nullable=False),
    sa.Column('from_address_id', sa.Integer(), nullable=False),
    sa.Column('to_address_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.index'], ),
    sa.ForeignKeyConstraint(['from_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['generated_carpool_id'], ['generated_carpools.id'], ),
    sa.ForeignKeyConstraint(['to_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_carpool_passenger_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_carpool_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generated_carpool_id'], ['generated_carpools.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.index'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_carpool_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_carpool_id', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['generated_carpool_id'], ['generated_carpools.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.index'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

# bruh its literally called bad3455643f1_.py :(

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_carpool_response')
    op.drop_table('generated_carpool_passenger_links')
    op.drop_table('generated_carpool_parts')
    op.drop_table('generated_carpools')
    op.drop_table('carpool_solutions')
    # ### end Alembic commands ###
