"""empty message

Revision ID: cbbb273d7902
Revises: 0bad6b0f4ae5
Create Date: 2022-11-09 19:39:01.408484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbb273d7902'
down_revision = '0bad6b0f4ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool_solutions', sa.Column('length_objective_value', sa.Float(), nullable=False))
    op.add_column('carpool_solutions', sa.Column('needed_passengers_served_objective_value', sa.Float(), nullable=False))
    op.add_column('carpool_solutions', sa.Column('favorable_time_objective_value', sa.Float(), nullable=False))
    op.add_column('carpool_solutions', sa.Column('favorable_route_objective_value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool_solutions', 'favorable_route_objective_value')
    op.drop_column('carpool_solutions', 'favorable_time_objective_value')
    op.drop_column('carpool_solutions', 'needed_passengers_served_objective_value')
    op.drop_column('carpool_solutions', 'length_objective_value')
    # ### end Alembic commands ###
