"""empty message

Revision ID: cfd50aee529f
Revises: 5ded14ca6717
Create Date: 2022-11-09 09:54:27.718633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfd50aee529f'
down_revision = '5ded14ca6717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_tasksetmeta')
    op.drop_table('celery_taskmeta')
    op.drop_constraint('distance_matrix_destination_id_fkey', 'distance_matrix', type_='foreignkey')
    op.drop_constraint('distance_matrix_origin_id_fkey', 'distance_matrix', type_='foreignkey')
    op.add_column('addresses', sa.Column('passenger_id', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.drop_constraint('addresses_destination_id_key', 'addresses', type_='unique')
    op.drop_constraint('addresses_origin_id_key', 'addresses', type_='unique')
    op.create_foreign_key(None, 'addresses', 'drivers', ['driver_id'], ['index'])
    op.create_foreign_key(None, 'addresses', 'passengers', ['passenger_id'], ['index'])
    op.drop_column('addresses', 'origin_id')
    op.drop_column('addresses', 'destination_id')
    op.create_foreign_key(None, 'distance_matrix', 'addresses', ['destination_id'], ['id'])
    op.create_foreign_key(None, 'distance_matrix', 'addresses', ['origin_id'], ['id'])
    op.create_foreign_key(None, 'drivers', 'regions', ['region_name'], ['name'])
    op.create_foreign_key(None, 'drivers', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key(None, 'events', 'addresses', ['address_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'passengers', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passengers', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'distance_matrix', type_='foreignkey')
    op.drop_constraint(None, 'distance_matrix', type_='foreignkey')
    op.create_foreign_key('distance_matrix_origin_id_fkey', 'distance_matrix', 'addresses', ['origin_id'], ['origin_id'])
    op.create_foreign_key('distance_matrix_destination_id_fkey', 'distance_matrix', 'addresses', ['destination_id'], ['destination_id'])
    op.add_column('addresses', sa.Column('destination_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('origin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_unique_constraint('addresses_origin_id_key', 'addresses', ['origin_id'])
    op.create_unique_constraint('addresses_destination_id_key', 'addresses', ['destination_id'])
    op.drop_column('addresses', 'driver_id')
    op.drop_column('addresses', 'passenger_id')
    op.create_table('celery_taskmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_taskmeta_pkey'),
    sa.UniqueConstraint('task_id', name='celery_taskmeta_task_id_key')
    )
    op.create_table('celery_tasksetmeta',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_tasksetmeta_pkey'),
    sa.UniqueConstraint('taskset_id', name='celery_tasksetmeta_taskset_id_key')
    )
    # ### end Alembic commands ###
