"""Super small update to add a type to carpool solutions

Revision ID: e7f22b2e6e0b
Revises: 18cd6c449934
Create Date: 2022-11-21 14:56:38.022532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f22b2e6e0b'
down_revision = '18cd6c449934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool_solutions', sa.Column('type', sa.String(length=4), nullable=True))
    op.execute("UPDATE carpool_solutions SET type = 'to' WHERE type IS NULL")
    op.alter_column('carpool_solutions', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpool_solutions', 'type')
    # ### end Alembic commands ###
