"""splitting the needs_matching_build column into two

Revision ID: ea4e8bf5d89e
Revises: dab91e5f9b09
Create Date: 2022-11-26 19:47:46.153739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4e8bf5d89e'
down_revision = 'dab91e5f9b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'needs_matching_build', new_column_name='needs_matching_build_from')
    op.add_column('events', sa.Column('needs_matching_build_to', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'needs_matching_build_from', new_column_name='needs_matching_build')
    op.drop_column('events', 'needs_matching_build_to')
    # ### end Alembic commands ###
